"""Add Message field

Revision ID: d06cef64dc2a
Revises: cd3ab3bf46ef
Create Date: 2024-08-25 14:18:06.082839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06cef64dc2a'
down_revision: Union[str, None] = 'cd3ab3bf46ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'meetingroom', ['meeting_room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('meeting_room_id')

    # ### end Alembic commands ###
